// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiQ-UkMs6oGpOY7nV9JE1xm12FmS5uUk0',
    appId: '1:359608376366:web:f38e0bc09b12a3063313bf',
    messagingSenderId: '359608376366',
    projectId: 'sliptrack-4a919',
    authDomain: 'sliptrack-4a919.firebaseapp.com',
    storageBucket: 'sliptrack-4a919.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsm4asoGUilv5FtvQqSBIpQZqVFRbM_Kk',
    appId: '1:359608376366:android:1f45b20064bcf41f3313bf',
    messagingSenderId: '359608376366',
    projectId: 'sliptrack-4a919',
    storageBucket: 'sliptrack-4a919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRJ21fpxrx47j10C-FKy1BiuvvRCGWw40',
    appId: '1:359608376366:ios:bacb274181f9d8b73313bf',
    messagingSenderId: '359608376366',
    projectId: 'sliptrack-4a919',
    storageBucket: 'sliptrack-4a919.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRJ21fpxrx47j10C-FKy1BiuvvRCGWw40',
    appId: '1:359608376366:ios:bacb274181f9d8b73313bf',
    messagingSenderId: '359608376366',
    projectId: 'sliptrack-4a919',
    storageBucket: 'sliptrack-4a919.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiQ-UkMs6oGpOY7nV9JE1xm12FmS5uUk0',
    appId: '1:359608376366:web:c5b23226c9bc6a6f3313bf',
    messagingSenderId: '359608376366',
    projectId: 'sliptrack-4a919',
    authDomain: 'sliptrack-4a919.firebaseapp.com',
    storageBucket: 'sliptrack-4a919.firebasestorage.app',
  );
}
